# Generated by Django 5.1.5 on 2025-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_teacher_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_approved_by_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_approved_by_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
