# Generated by Django 5.1.5 on 2025-01-20 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_student_is_approved_by_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('step_1_completed', models.BooleanField(default=False)),
                ('step_2_completed', models.BooleanField(default=False)),
                ('step_3_completed', models.BooleanField(default=False)),
                ('step_4_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
